### ISSUE TITLE
Make VSync work (not priority)

### ISSUE THREAD

**Issue by Montuuh** [WillyTrek19/Project-19-2000#93]
When toggling the VSync, the renderer must be destroyed and recreated again. Refer to Render.cpp line 300.
The uptime code doesnt create correctly the renderer again. All pointers would be necessary to restart also.
Some idea could be to make the VSync checkbox only available for the user at the main menu options. Making it easy to restart everything, not letting the user to toggle VSync in the middle of the gameplay.

**Comment by KiwiTrek** [comment]
This is unable to be done in SDL efficiently and with security.
